services:
  n8n:
    environment:
      EXECUTIONS_DATA_SAVE_ON_ERROR: all
      EXECUTIONS_DATA_SAVE_ON_SUCCESS: all
      EXECUTIONS_DATA_SAVE_ON_PROGRESS: "false"
      EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS: "true"
      EXECUTIONS_DATA_PRUNE: "${TANAGHOM_RETENTION_TEST_PRUNE:-false}"
      EXECUTIONS_DATA_MAX_AGE: "8760"
      EXECUTIONS_DATA_PRUNE_MAX_COUNT: "${TANAGHOM_RETENTION_TEST_MAX_COUNT:-20}"
      EXECUTIONS_DATA_HARD_DELETE_BUFFER: "0"
      EXECUTIONS_DATA_PRUNE_HARD_DELETE_INTERVAL: "1"
      EXECUTIONS_DATA_PRUNE_SOFT_DELETE_INTERVAL: "1"

  n8n-worker:
    environment:
      EXECUTIONS_DATA_SAVE_ON_ERROR: all
      EXECUTIONS_DATA_SAVE_ON_SUCCESS: all
      EXECUTIONS_DATA_SAVE_ON_PROGRESS: "false"
      EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS: "true"
      EXECUTIONS_DATA_PRUNE: "${TANAGHOM_RETENTION_TEST_PRUNE:-false}"
      EXECUTIONS_DATA_MAX_AGE: "8760"
      EXECUTIONS_DATA_PRUNE_MAX_COUNT: "${TANAGHOM_RETENTION_TEST_MAX_COUNT:-20}"
      EXECUTIONS_DATA_HARD_DELETE_BUFFER: "0"
      EXECUTIONS_DATA_PRUNE_HARD_DELETE_INTERVAL: "1"
      EXECUTIONS_DATA_PRUNE_SOFT_DELETE_INTERVAL: "1"
