#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
RELEASE_SOURCE_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/../../.." && pwd)
CURRENT=1111111111111111111111111111111111111111
TARGET=2222222222222222222222222222222222222222
RELEASE=phase5c-worker-20260721T120000Z

expect_refusal() {
  if "$@" >/dev/null 2>&1; then echo 'expected refusal unexpectedly succeeded' >&2; exit 1; fi
}

expect_refusal env TANAGHOM_WORKER_COMMON_DIR="$SCRIPT_DIR" TANAGHOM_RELEASE_SOURCE_ROOT="$RELEASE_SOURCE_ROOT" TANAGHOM_WORKER_RELEASE_ID="$RELEASE" \
  TANAGHOM_EXPECTED_CURRENT_COMMIT="$CURRENT" TANAGHOM_TARGET_COMMIT="$TARGET" \
  sh -c ". '$SCRIPT_DIR/common.sh'; require_release_environment"

expect_refusal env TANAGHOM_WORKER_COMMON_DIR="$SCRIPT_DIR" TANAGHOM_RELEASE_SOURCE_ROOT="$RELEASE_SOURCE_ROOT" TANAGHOM_WORKER_RELEASE_AUTHORIZATION=YES-I-AM-THE-AUTHORIZED-OWNER \
  TANAGHOM_WORKER_RELEASE_ID=unsafe TANAGHOM_EXPECTED_CURRENT_COMMIT="$CURRENT" TANAGHOM_TARGET_COMMIT="$TARGET" \
  sh -c ". '$SCRIPT_DIR/common.sh'; require_release_environment"

expect_refusal env TANAGHOM_WORKER_COMMON_DIR="$SCRIPT_DIR" TANAGHOM_RELEASE_SOURCE_ROOT="$RELEASE_SOURCE_ROOT" TANAGHOM_WORKER_RELEASE_AUTHORIZATION=YES-I-AM-THE-AUTHORIZED-OWNER \
  TANAGHOM_WORKER_RELEASE_ID="$RELEASE" TANAGHOM_EXPECTED_CURRENT_COMMIT="$CURRENT" TANAGHOM_TARGET_COMMIT="$CURRENT" \
  sh -c ". '$SCRIPT_DIR/common.sh'; require_release_environment"

env TANAGHOM_WORKER_COMMON_DIR="$SCRIPT_DIR" TANAGHOM_RELEASE_SOURCE_ROOT="$RELEASE_SOURCE_ROOT" TANAGHOM_WORKER_RELEASE_AUTHORIZATION=YES-I-AM-THE-AUTHORIZED-OWNER \
  TANAGHOM_WORKER_RELEASE_ID="$RELEASE" TANAGHOM_EXPECTED_CURRENT_COMMIT="$CURRENT" TANAGHOM_TARGET_COMMIT="$TARGET" \
  sh -c ". '$SCRIPT_DIR/common.sh'; require_release_environment; test \"\$TANAGHOM_RELEASE_ID\" = '$RELEASE'"

grep -q 'ROLLBACK_FAILED=YES' "$SCRIPT_DIR/deploy-update.sh"
grep -q 'active IS FALSE' "$SCRIPT_DIR/common.sh"
grep -q 'ROLLBACK-THE-AUTHORIZED-CONVERSATION-WORKER-RELEASE' "$SCRIPT_DIR/rollback-update.sh"

echo 'PASS: missing authorization, invalid IDs, and unsafe commit identities are refused.'
